# Generated by Django 4.1.7 on 2023-03-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ('position',)},
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('is_special', models.BooleanField(default=True)),
                ('is_signature', models.BooleanField(default=True)),
                ('is_recomendet', models.BooleanField(default=True)),
                ('desc', models.TextField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount', models.PositiveSmallIntegerField(default=0)),
                ('ingradients', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='dishes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dishcategory')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
