# Generated by Django 4.1.7 on 2023-03-06 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_dishcategory_options_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.TextField(blank=True, max_length=4000)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main_app.dishcategory'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='discount',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
