# Generated by Django 4.1.7 on 2023-03-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_about_alter_dish_category_alter_dish_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_clean_environment', models.CharField(max_length=100, unique=True)),
                ('body_clean_environment', models.TextField(max_length=4000, unique=True)),
                ('title_expert_chefs', models.CharField(max_length=100, unique=True)),
                ('body_expert_chefs', models.TextField(max_length=4000, unique=True)),
                ('title_tasty_food', models.CharField(max_length=100, unique=True)),
                ('body_tasty_food', models.TextField(max_length=4000, unique=True)),
            ],
        ),
    ]
