# Generated by Django 4.1.7 on 2023-03-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_dish_options_alter_dishcategory_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='body_clean_environment',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title_clean_environment',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='body_expert_chefs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='body_tasty_food',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_expert_chefs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='title_tasty_food',
        ),
        migrations.AddField(
            model_name='service',
            name='clean_environment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='expert_chefs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='tasty_food',
            field=models.BooleanField(default=False),
        ),
    ]
