# Generated by Django 4.1.7 on 2023-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_rename_body_clean_environment_service_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='year_in_school',
            field=models.CharField(choices=[('M', 'CLEAN ENVIRONMENT'), ('E', 'Sexpert_chefs'), ('F', 'tasty_food')], default='M', max_length=2),
        ),
    ]
