# Generated by Django 4.1.7 on 2023-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_service_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='clean_environment',
        ),
        migrations.RemoveField(
            model_name='service',
            name='expert_chefs',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tasty_food',
        ),
        migrations.AlterField(
            model_name='service',
            name='year_in_school',
            field=models.CharField(choices=[('M', 'clean environment'), ('E', 'Sexpert chefs'), ('F', 'tasty food')], default='M', max_length=2),
        ),
    ]
