# Generated by Django 4.1.7 on 2023-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_service_clean_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='body',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='service',
            name='year_in_school',
            field=models.CharField(choices=[('M', 'clean environment'), ('E', 'sexpert chefs'), ('F', 'tasty food')], default='M', max_length=2),
        ),
    ]
