# Generated by Django 4.1.7 on 2023-03-10 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_year_in_school_service_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='the number should have the following format: +380xx xxx xx xx', regex='^+?3?8?0?\\d{2}[ -]?(\\d[ -]?){7}$')])),
                ('date', models.DateTimeField()),
                ('date_request', models.DateTimeField(auto_now_add=True)),
                ('date_response', models.DateTimeField(auto_now=True)),
                ('quests', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=1000)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date_request',),
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('-position',)},
        ),
    ]
